#!/bin/sh
set -e

FTPENTRY="ftp		stream	tcp	nowait	root	/usr/sbin/tcpd	/usr/sbin/uftpd -i -f"
TFTPENTRY="tftp		dgram	udp	nowait	root	/usr/sbin/tcpd	/usr/sbin/uftpd -i -t"

if [ ! -f /etc/inetd.conf -a -d /etc/xinetd.d -a -x /usr/sbin/xinetd ]; then
	cat <<-TEXT
		-------------------------------------------------
		There is no configuration support for using uftpd
		under the control of xinetd.
		-------------------------------------------------
	TEXT
fi

if grep -q '[[:blank:]]/usr/sbin/uftpd.*' /etc/inetd.conf 2>/dev/null; then
	update-inetd --pattern '/usr/sbin/uftpd' --remove ".*ftp"
fi

update-inetd --group STANDARD --add "$FTPENTRY"
update-inetd --group STANDARD --add "$TFTPENTRY"

if ! grep -q "^ftp:" /etc/passwd; then
	addgroup --quiet --system ftp
	adduser --quiet --system --disabled-login --home /srv/ftp --ingroup ftp ftp || true
fi

# Adjust for any previous server, users wanting to share files with
# TFTP/FTP should be in the ftp group
chown --changes ftp:ftp /srv/ftp
chmod --changes 0775 /srv/ftp

update-inetd --pattern '/usr/sbin/uftpd' --enable ".*ftp"
