#!/bin/sh

set -e

if grep -q '[[:blank:]]/usr/sbin/uftpd.*-z' /etc/inetd.conf 2>/dev/null; then
	update-inetd --pattern '/usr/sbin/uftpd' --remove ".*ftp"
fi

if grep -q '[[:blank:]]/usr/sbin/uftpd\>' /etc/inetd.conf 2>/dev/null; then
	if ! grep -q '^ftp\>' /etc/inetd.conf; then
		update-inetd --pattern '/usr/sbin/uftpd' --multi --enable ftp
	fi
else
	FTPENTRY="ftp		stream	tcp	nowait	root	/usr/sbin/tcpd	/usr/sbin/uftpd -i"
	if grep -q '^ftp\>' /etc/inetd.conf 2>/dev/null; then
		update-inetd --group STANDARD --add "## $FTPENTRY"
	else
		update-inetd --group STANDARD --add "$FTPENTRY"
	fi
fi

if [ ! -f /etc/inetd.conf -a -d /etc/xinetd.d -a -x /usr/sbin/xinetd ]; then
	cat <<-TEXT
		-------------------------------------------------
		There is no configuration support for using uftpd
		under the control of xinetd.
		-------------------------------------------------
	TEXT
fi

if ! grep -q "^ftp:" /etc/passwd; then
	addgroup --quiet --system ftp
	adduser --quiet --system --disabled-login --home /srv/ftp --ingroup ftp ftp || true
fi

#DEBHELPER#
