#!/bin/sh -e

if [ "$1" = "purge" ]; then
	if command -v update-inetd >/dev/null 2>&1; then
		update-inetd --pattern 'uftpd' --remove ".*ftp"
		update-inetd --pattern 'in.ftpd' --remove ftp
		update-inetd --pattern 'in.tftpd' --remove tftp
	fi

	# Remove uftpd entries from db
	if [ -f /usr/share/debconf/confmodule ]; then
		. /usr/share/debconf/confmodule
		db_purge uftpd/ftp
		db_purge uftpd/tftp
	fi
fi

deluser ftp || true

exit 0
