#!/bin/sh

set -e

# Source debconf library.
. /usr/share/debconf/confmodule

db_get uftpd/ftp
[ "$RET" = "true" ] && update-inetd --pattern '/usr/sbin/in.ftpd' --multi --disable ftp
db_get uftpd/tftp
[ "$RET" = "true" ] && update-inetd --pattern '/usr/sbin/in.tftpd' --multi --disable tftp

#DEBHELPER#
